/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Serve the main dashboard
         */
        get: operations["dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team-members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Members
         * @description Get all team members
         */
        get: operations["get_team_members_api_team_members_get"];
        put?: never;
        /**
         * Add Team Member Api
         * @description Add team member via API
         */
        post: operations["add_team_member_api_api_team_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prospects
         * @description Get prospects with optional status filter
         */
        get: operations["get_prospects_api_prospects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/introductions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Introductions
         * @description Get introduction requests
         */
        get: operations["get_introductions_api_introductions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Get dashboard analytics
         */
        get: operations["get_analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics Overview
         * @description Return normalized analytics data for the dashboard cards.
         */
        get: operations["get_analytics_overview_api_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Flags Api
         * @description Expose evaluated feature flags for clients.
         */
        get: operations["get_feature_flags_api_api_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Workflow
         * @description Stop an automated workflow execution.
         */
        post: operations["stop_workflow_api_workflows__workflow_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload-prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Prospects Endpoint
         * @description Upload prospects CSV file
         */
        post: operations["upload_prospects_endpoint_api_upload_prospects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/introductions/{intro_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Introduction
         * @description Delete an introduction request
         */
        delete: operations["delete_introduction_api_introductions__intro_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prospects/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Prospects
         * @description Bulk update prospect status
         */
        post: operations["bulk_update_prospects_api_prospects_bulk_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prospects/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Delete Prospects
         * @description Bulk delete prospects
         */
        post: operations["bulk_delete_prospects_api_prospects_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/introductions/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Introductions
         * @description Bulk update introduction status
         */
        post: operations["bulk_update_introductions_api_introductions_bulk_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsOverviewPayload */
        AnalyticsOverviewPayload: {
            /** Totals */
            totals: {
                [key: string]: unknown;
            };
            /** Pipeline */
            pipeline: {
                [key: string]: unknown;
            };
            /** Performance */
            performance: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** AnalyticsOverviewResponse */
        AnalyticsOverviewResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["AnalyticsOverviewPayload"];
        };
        /** AnalyticsPayload */
        AnalyticsPayload: {
            /** Prospects */
            prospects: {
                [key: string]: unknown;
            };
            /** Connectors */
            connectors: {
                [key: string]: unknown;
            };
            /** Workflows */
            workflows: {
                [key: string]: unknown;
            };
            /** Quotas */
            quotas: {
                [key: string]: unknown;
            };
            /** Integrations */
            integrations: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** AnalyticsResponse */
        AnalyticsResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["AnalyticsPayload"];
        };
        /** Body_upload_prospects_endpoint_api_upload_prospects_post */
        Body_upload_prospects_endpoint_api_upload_prospects_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BulkOperationPayload */
        BulkOperationPayload: {
            /** Message */
            message?: string | null;
            /** Updated Count */
            updated_count?: number | null;
            /** Deleted Count */
            deleted_count?: number | null;
        };
        /** BulkOperationResponse */
        BulkOperationResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["BulkOperationPayload"];
        };
        /** FeatureFlagMap */
        FeatureFlagMap: {
            /** Flags */
            flags: {
                [key: string]: boolean;
            };
            /** Evaluated At */
            evaluated_at: string;
            /** Source */
            source: string;
        } & {
            [key: string]: unknown;
        };
        /** FeatureFlagResponse */
        FeatureFlagResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["FeatureFlagMap"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Overall service health indicator
             * @default healthy
             */
            status: string;
            /**
             * Service
             * @description Name of the responding service
             */
            service: string;
        };
        /** Introduction */
        Introduction: {
            /** Id */
            id: number;
            /** Prospect Id */
            prospect_id?: number | null;
            /** Team Member Id */
            team_member_id?: number | null;
            /** Introduction Message */
            introduction_message?: string | null;
            /** Status */
            status?: string | null;
            /** Created Date */
            created_date?: string | null;
            /** Sent Date */
            sent_date?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IntroductionListResponse */
        IntroductionListResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            /** Data */
            data: components["schemas"]["Introduction"][];
        };
        /** Prospect */
        Prospect: {
            /** Id */
            id: number;
            /** Full Name */
            full_name?: string | null;
            /** Company */
            company?: string | null;
            /** Headline */
            headline?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Status */
            status?: string | null;
            /** User Id */
            user_id?: number | null;
            /** Tenant Id */
            tenant_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ProspectListResponse */
        ProspectListResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            /** Data */
            data: components["schemas"]["Prospect"][];
        };
        /** ProspectUploadPayload */
        ProspectUploadPayload: {
            /**
             * Uploaded Count
             * @description Number of prospects uploaded successfully
             */
            uploaded_count: number;
            /** Validation */
            validation: {
                [key: string]: unknown;
            };
            /** Match Results */
            match_results: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** ProspectUploadResponse */
        ProspectUploadResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["ProspectUploadPayload"];
        };
        /** TeamMember */
        TeamMember: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
            /** Tenant Id */
            tenant_id?: string | null;
            /** Total Connections */
            total_connections?: number | null;
            /** Last Scan Date */
            last_scan_date?: string | null;
            /** Cookie Status */
            cookie_status?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TeamMemberCreatePayload */
        TeamMemberCreatePayload: {
            /** Member Id */
            member_id: number;
        };
        /** TeamMemberCreateResponse */
        TeamMemberCreateResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["TeamMemberCreatePayload"];
        };
        /** TeamMemberListResponse */
        TeamMemberListResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            /** Data */
            data: components["schemas"]["TeamMember"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowStopPayload */
        WorkflowStopPayload: {
            /** Workflow Id */
            workflow_id: string;
            /** Cancelled */
            cancelled: boolean;
            /** Reason */
            reason: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: number;
        };
        /** WorkflowStopResponse */
        WorkflowStopResponse: {
            /**
             * Status
             * @description success or error
             */
            status: string;
            /**
             * Message
             * @description Optional human readable message
             */
            message?: string | null;
            data: components["schemas"]["WorkflowStopPayload"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_team_members_api_team_members_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_team_member_api_api_team_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prospects_api_prospects_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_introductions_api_introductions_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntroductionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_analytics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_overview_api_analytics_overview_get: {
        parameters: {
            query?: {
                days?: number;
                organization_id?: number | null;
            };
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_flags_api_api_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagResponse"];
                };
            };
        };
    };
    stop_workflow_api_workflows__workflow_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                "x-tenant-id"?: string | null;
                "x-user-id"?: string | null;
            };
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_prospects_endpoint_api_upload_prospects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_prospects_endpoint_api_upload_prospects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_introduction_api_introductions__intro_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intro_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_prospects_api_prospects_bulk_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_prospects_api_prospects_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_introductions_api_introductions_bulk_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
